spring.application.name=ai-summariser
# Server Configuration
server.port=8080

# Gemini API Configurations
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.8-flash:generateContent
gemini.api.key= API-KEY

